// Run against a static server: node tests/browser-enemies.cjs
const fs=require('node:fs'),path=require('node:path');
const output=process.env.PREVIEW_OUTPUT||'/tmp/jules-enemy-preview';fs.mkdirSync(output,{recursive:true});
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1280,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8000/concepts/v4-enemy-encounters.html');await p.waitForTimeout(800);
for(let i=1;i<=30;i++){await p.evaluate(i=>{EnemyStudy.select('enc_'+i);EnemyStudy.pause();EnemyStudy.step(12);},i);}assert.equal(await p.locator('.shot').count(),18);await p.evaluate(()=>{EnemyStudy.select('enc_22');EnemyStudy.pause();EnemyStudy.step(3.5);EnemyStudy.shots(.7);});await p.screenshot({path:path.join(output,'enemy-desktop.png'),fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(output,'enemy-mobile.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.goto('http://127.0.0.1:8000/concepts/v4-skill-effects.html');await p.waitForTimeout(100);for(const id of await p.evaluate(()=>SkillStudy.ids))await p.evaluate(id=>{SkillStudy.select(id);SkillStudy.seek(1.8);},id);
await p.goto('http://127.0.0.1:8000/v4/');await p.evaluate(()=>{__g.newRun('easy');__g.enterNode(__g.R.map.floors[0][0]);});await p.waitForTimeout(100);await p.screenshot({path:path.join(output,'game-new-enemies.png'),fullPage:true});const stored=await p.evaluate(()=>JSON.stringify({enemies:__g.R.enemies,encounters:__g.R.encounters,round:__g.R.round}));
await p.reload();await p.locator('#contBtn').click();await p.locator('#scr-play').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>JSON.stringify({enemies:__g.R.enemies,encounters:__g.R.encounters,round:__g.R.round})),stored);
await p.evaluate(()=>{const r=__g.R;r.board=[{kind:'unit',id:'archer',uid:'check-archer',star:2,skills:[],item:null,x:1,y:4},{kind:'unit',id:'pyro',uid:'check-pyro',star:2,skills:[],item:null,x:3,y:4}];__g.renderPlay();__g.startCombat();});
await p.locator('#skipBtn').click();await p.locator('#resBtn').waitFor({state:'visible',timeout:20000});
console.log(JSON.stringify({errors,shots:18,encounters:30,prepSaveResume:true,skip:true}));assert.deepEqual(errors,[]);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
