const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function world(){const c={};c.window=c;vm.createContext(c);for(const f of ['shared/engine.js','game/data.js','v4/data4.js','v4/enemies4.js','v4/encounters4.js','v4/enemy-combat4.js','v4/battle4.js','v4/save4.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);return c;}
function state(c){const floors=Array.from({length:6},(_,f)=>[{id:'1-'+f,f,x:.5,k:f===5?'boss':'fight',next:f===5?[]:['1-'+(f+1)]}]);return {v:4,act:1,round:0,lv:3,gold:6,xp:0,diff:'normal',mode:'map',relics:[],pool:{},board:[],bench:Array(8).fill(null),shop:{unit:[],skill:[],item:[]},map:{act:1,floors,boss:c.GD.ACTS[1].bosses[0]},pos:null,path:[],node:null,enemies:[],stats:{wins:0,battles:0,merges:0,goldEarned:0,kills:0,time:0,elites:0,bosses:0}};}
function memory(){const values=new Map();return {values,getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};}
test('save migration validates before exposing state, preserving old v4 and repairing starred pools',()=>{const c=world(),s=state(c);s.bench[0]={kind:'item',id:'longsword',uid:'it',star:2};s.pool['item:longsword']=29;const r=c.SAVE4.normalize(s);assert.ok(r);assert.equal(r.saveVersion,1);assert.equal(r.pool['item:longsword'],27);assert.equal(s.pool['item:longsword'],29);assert.ok(Number.isInteger(r.battleSeed));});
test('malformed fields, pending stages and future versions are rejected safely',()=>{const c=world();for(const change of [s=>s.saveVersion=99,s=>s.board=[{kind:'unit',id:'removed',star:1}],s=>s.stats=null,s=>s.gold=-1,s=>s.map.floors=null,s=>s.relics={},s=>s.enemies=[{id:'missing',cell:0}],s=>s.pending={type:'arbitrary'},s=>s.mode='result']){const s=state(c);change(s);assert.equal(c.SAVE4.normalize(s),null);}assert.equal(c.SAVE4.normalize({}),null);assert.equal(c.SAVE4.normalize(null),null);});
test('backup survives invalid writes and restores a corrupt primary; clear removes both',()=>{const c=world(),m=memory(),store=c.SAVE4.create(m,'run'),s=state(c);assert.equal(store.write(s),true);s.gold=12;assert.equal(store.write(s),true);assert.equal(store.write({}),false);assert.equal(store.read().run.gold,12);m.setItem('run','{broken');assert.equal(store.read().status,'recovered');assert.equal(store.read().run.gold,6);store.clear();assert.equal(store.read().status,'empty');assert.equal(m.values.size,0);});
test('storage denial and quota exhaustion return an explicit failure',()=>{const c=world(),m={getItem(){throw Error('denied')},setItem(){throw Error('quota')},removeItem(){throw Error('denied')}};const store=c.SAVE4.create(m,'run');assert.equal(store.read().status,'unavailable');assert.equal(store.write(state(c)),false);assert.equal(store.clear(),false);});
test('pending relic plus pre-rolled boss cards survives round trip',()=>{const c=world(),s=state(c),n=s.map.floors[5][0];s.node={id:n.id,k:n.k,f:n.f};s.round=6;s.mode='rest';s.pending={type:'relic',title:'보스 전리품',options:['phoenix'],next:{type:'reward',title:'보스 전리품',sub:'선택',cards:[{kind:'item',id:'longsword',star:1,uid:'loot'}]}};const r=c.SAVE4.normalize(s);assert.ok(r);assert.equal(JSON.stringify(r.pending),JSON.stringify(s.pending));});
function combat(c,act,seed,noise){const random=c.AC.rng(seed),grid=c.AC.squareGrid(5,6,64),r={act,round:act*6,relics:[],diff:'normal'},api=c.BT4.create({grid,PLAYER_ROW:3,COLS:5,ROWS:6,getR:()=>r,random,phase(){},fx:{play:noise,shake:noise,burst:noise,death:noise,skill:noise}});const board=['warden','paladin','blademaster','ninja','archmage','cryo','bishop'].map((id,i)=>({id,uid:'u'+i,star:2,skills:[{id:i<3?'cross':i===3?'ice':'chain',star:2}],item:null,x:i%5,y:i<3?3:5}));const syn=api.synergyCounts(board),us=board.map(u=>api.makeAlly(u,grid.idx(u.x,u.y),syn));for(const [i,id]of [c.GD.ACTS[act].bosses[seed%2],c.GD.ACTS[act].normal.at(-1)].entries())us.push(api.makeFoe({def:c.GD.MONSTERS[id],cell:grid.idx(i+2,1),scale:1}));return new c.AC.Combat(grid,us,{random,hooks:api.hooks(),maxTime:150});}
function digest(cb){return JSON.stringify({winner:cb.winner,t:cb.t,units:cb.units.map(u=>({id:u.def.id,cell:u.cell,hp:u.hp,dead:u.dead,shield:u.shield,casts:u.castCount,dmg:u.dmgDealt}))});}
test('all five acts: independent combat streams withstand arbitrary visual RNG and interleaved fights',()=>{const c=world();for(let act=1;act<=5;act++){const a=combat(c,act,act,()=>{}),b=combat(c,act,act,()=>{for(let i=0;i<25;i++)vm.runInContext('Math.random()',c);});while(!a.done||!b.done){if(!a.done)a.step(1/60);vm.runInContext('Math.random(); Math.random();',c);if(!b.done)b.step(1/60);}assert.equal(digest(a),digest(b),'act '+act);}});
